This notebook contains code to **process** raw 'beta' and 'Marketcap' data retreived, to generate description. It requires input file ```data_beta_marketcap_raw.csv```

In [1]:
import pandas as pd

# load raw df for preprocessing
df = pd.read_csv('data_beta_marketcap_raw.csv')

# generate an "absolute value" column for beta
df['Beta_abs'] = df['Beta'].abs()

# sort df by market cap
df = df.sort_values(by=['Marketcap'],ignore_index=True, ascending=False)

# drop entries with no data. These include (but are not limited to) 
    # newly listed companies with no data, 
    # delisted companies
    # ETFs with no applicable "market cap" values
df = df.dropna()
# reset index
df = df.reset_index(drop=True)
df

      Stock      Beta     Marketcap  Beta_abs
0    D05.SI  0.976465  8.871046e+10  0.976465
1    O39.SI  0.738125  5.497841e+10  0.738125
2    U11.SI  0.923406  4.898195e+10  0.923406
3    Z77.SI  0.554985  4.412701e+10  0.554985
4    Z74.SI  0.554985  4.293475e+10  0.554985
..      ...       ...           ...       ...
569  BKK.SI -1.136927  2.277000e+06  1.136927
570  BFK.SI  0.296534  2.185000e+06  0.296534
571  AWM.SI  0.115960  1.861720e+06  0.115960
572  BOU.SI  1.433889  1.418720e+06  1.433889
573  AYV.SI  0.229459  1.398903e+06  0.229459

[574 rows x 4 columns]

In [2]:
# generate subset of top and bottom 50 market cap firm
df_top50 = df.head(50)
df_btm50 = df.tail(50)

In [3]:
# top 50 market cap stocks listed on SGX
df_top50.describe()

            Beta     Marketcap   Beta_abs
count  50.000000  5.000000e+01  50.000000
mean    0.687463  1.289992e+10   0.688438
std     0.290870  1.700238e+10   0.288506
min    -0.024390  2.432108e+09   0.024390
25%     0.508129  3.388812e+09   0.508129
50%     0.686563  5.385304e+09   0.686563
75%     0.900192  1.283969e+10   0.900192
max     1.285836  8.871046e+10   1.285836

In [4]:
# bottom 50 market cap stocks listed on SGX
df_btm50.describe()

            Beta     Marketcap   Beta_abs
count  50.000000  5.000000e+01  50.000000
mean    0.855276  5.923673e+06   1.084475
std     1.220928  2.147996e+06   1.018333
min    -1.766795  1.398903e+06   0.031236
25%     0.229885  4.548393e+06   0.410663
50%     0.818858  6.060580e+06   0.852137
75%     1.384882  7.566888e+06   1.405220
max     5.872058  9.382120e+06   5.872058

In [5]:
# all stocks listed on SGX
df.describe()

             Beta     Marketcap    Beta_abs
count  574.000000  5.740000e+02  574.000000
mean     0.653968  1.324293e+09    0.730368
std      0.697116  6.138819e+09    0.616460
min     -1.766795  1.398903e+06    0.000000
25%      0.296213  2.150252e+07    0.346812
50%      0.584082  6.678633e+07    0.598844
75%      0.918805  3.229064e+08    0.945657
max      5.872058  8.871046e+10    5.872058